PlayMaker-S/Sports-IT-Next

- src/api/account/accountApi.ts
- src/atoms/tokenAtom.ts
- src/interfaces/accountInterface.ts
- src/pages/auth/login.tsx
- src/pages/auth/signup.styles.ts
- src/pages/auth/signup.tsx
- src/pages/register/contest-info.styles.ts
- src/pages/register/contest-info.tsx
- 로그인 API 수정 및 연동
- 회원가입 UI 수정
- 회원가입 API 수정 및 연동
<br/>
- 디자인 수정
- 테스트
<br/>
- 없습니다.
<br/><br/>
> 로그인(login.tsx) 및 회원가입(signup.tsx) UI 및 API 수정사항 반영완료

- src/pages/register/contest-detail.tsx
- src/pages/register/contest-info.tsx
- src/pages/register/headcount.styles.ts
- 대회 상세정보 입력 페이지(contest-detail.tsx) 제작
- 다중 이미지 업로드 기능 구현
- 이미지 미리보기 기능 구현
- 이미지 삭제 기능 구현
<br/>
- 신규 기능 추가
<br/>
- 사진 최대 업로드 개수는 3개로 지정
- interface와 style 모듈화는 다음 작업 때 바로 진행하도록 하겠습니다 :)
<br/><br/>
> 대회 상세정보 입력 페이지(contest-detail.tsx) 제작 / 다중 이미지 업로드, 미리보기 기능 구현

- src/components/container/container.ts
- src/components/navbar/BottomBar.tsx
- src/components/navbar/NavBar.tsx
- src/interfaces/navInterface.ts
- src/pages/auth/event-select.tsx
- src/pages/auth/role-select.tsx
- src/pages/auth/signup.tsx
- src/pages/auth/terms.tsx
- src/pages/contest/index.tsx
- src/pages/participate/payment.tsx
- src/pages/register/contest-detail.tsx
- src/pages/register/contest-info.tsx
- src/pages/register/event-select.tsx
- src/pages/register/form.tsx
- src/pages/register/headcount.tsx
- src/pages/register/load-rules.tsx
- src/pages/register/make-survey.tsx
- src/pages/register/participation-cost.tsx
- src/pages/register/register-success.tsx
- src/pages/register/rules-and-terms.tsx
- src/pages/register/sector-and-weight.tsx
- 네비게이션 바 props 추가
- 바텀바 제작 및 컴포넌트화
- 대회 개최에 필요한 페이지 생성 및 라우팅
<br/>
- 디자인
- 리펙토링
<br/>
- 대회 개최 시나리오에 필요한 페이지들 생성 후 라우팅 해놓았고, 완성되지 않은 나머지 페이지는 완성되는 대로 pr 올리겠습니다 !
<br/><br/>
> [design&refactor] Navigation Bar 수정 및 Bottom Bar 생성 /  대회 개최 페이지 라우팅

- src/components/button/buttonComponent.ts
- src/components/input/inputComponent.ts
- src/pages/contest/index.styles.ts
- src/pages/register/rules-and-terms.styles.ts
- src/pages/register/rules-and-terms.tsx
- input box 컴포넌트화(components/input/inputComponent.ts)
- button 컴포넌트화(components/button/buttonComponent.ts)
- 규정 및 약관 등록 페이지(rules-and-terms.tsx) 제작
<br/>
- 디자인
- 코드 리팩토링
<br/>
- 규정 및 약관 페이지는 현재 디자인 및 라우팅까지 진행된 상황이고, 금일 내로 업로드 및 추가 기능 구현하도록 하겠습니다.
<br/><br/>
> [design] 규정 및 약관 등록 페이지 제작 / input 및 button 컴포넌트화

- src/components/area/areaComponent.ts
- src/pages/register/contest-detail.tsx
- src/pages/register/rules-and-terms.styles.ts
- src/pages/register/rules-and-terms.tsx
- 규정 및 약관 페이지(rules-and-terms.tsx) 파일 업로드 기능 구현
- 특정 UI 컴포넌트화
<br/>
- 신규 기능 추가
- 코드 리팩토링
<br/>
- 없습니다.
<br/><br/>
> [feat] 규정 및 약관 페이지 파일 및 URL 업로드 기능 구현

- src/atoms/contestAtom.ts
- src/components/card/ApplySurveyCard.styles.ts
- src/components/card/ApplySurveyCard.tsx
- src/components/card/SurveyCard.tsx
- src/components/navbar/NavBar.styles.ts
- src/interfaces/weightCostInterface.ts
- src/pages/participate/apply.styles.ts
- src/pages/participate/apply.tsx
- src/pages/participate/check-weight-sector.styles.ts
- src/pages/participate/check-weight-sector.tsx
- src/pages/participate/choice-role.tsx
- src/pages/participate/terms.tsx
- src/pages/register/event-select.tsx
- src/pages/register/form.styles.ts
- participate 페이지 제작
- register & components 코드 리팩토링
- 대회 신청 중 결제금액과 종목 선택 저장을 위한 Atom 및 State 코드
<br/>
- 신규 기능 추가
- 버그 수정
- 리펙토링
<br/>
- firebase 연동 후 동적으로 내용이 변경되어야 할 것 같습니다
<br/><br/>
> [feat & refactor] participate contest + refactor  codes

- src/atoms/contestAtom.ts
- src/pages/register/contest-detail.styles.ts
- src/pages/register/contest-detail.tsx
- src/pages/register/contest-info.styles.ts
- src/pages/register/contest-info.tsx
- src/pages/register/headcount.styles.ts
- src/pages/register/headcount.tsx
- 대회 개최에 필요한 전역 상태 관리
- 페이지 전체적인 CSS 및 요소 수정
<br/>
- 리팩토링
- 버그 수정
<br/>
- X
<br/><br/>
> [feat] Set atom value to headcount/contest-info/contest-detail page

- src/pages/register/contest-detail.tsx
- src/pages/register/contest-info.tsx
- src/pages/register/event-select.tsx
- src/pages/register/form.tsx
- src/pages/register/headcount.styles.ts
- src/pages/register/headcount.tsx
- src/pages/register/sector-and-weight.tsx
- 대회 개최 페이지(sector-and-weight.tsx) 기본정보 등록 테스트
- 대회 종목 영문화 함수 제작
<br/>
- 신규 기능 추가
- 통합 테스트
<br/>
- 없습니다.
<br/><br/>
> [feat] 대회 개최 페이지(sector-and-weight.tsx) 기본정보 등록 테스트 완료

- src/atoms/contestAtom.ts
- src/components/container/MainPageCompetition.tsx
- src/components/contest/Contest.tsx
- src/pages/contest/[id].styles.ts
- src/pages/contest/[id].tsx
- src/pages/contest/index.styles.ts
- src/pages/contest/index.tsx
- src/pages/index.tsx
- src/pages/participate/check-weight-sector.styles.ts
- src/pages/participate/check-weight-sector.tsx
- src/pages/participate/payment.styles.ts
- src/pages/participate/payment.tsx
- 총 결제 금액 계산 로직 구현
- 결제 페이지(payment.tsx) 디자인 완성
- 대회 이미지 경로 수정
- 일부 디자인 수정
<br/>
- 신규 기능 추가
- 버그 수정
- 리펙토링
<br/>
- 현재 import 결제 API 연동중에 있고, 연동 완료되면 PR 올리도록 하겠습니다.
<br/><br/>
> [feat&fix] 대회 관련 버그 수정 / 결제 페이지(payment.tsx) 로직 구현 완료

- src/atoms/contestAtom.ts
- src/components/area/areaComponent.ts
- src/components/container/ImageSlider.tsx
- src/components/container/MainPageRecommanduser.tsx
- src/components/container/Profile.tsx
- src/components/container/mainpagepost.tsx
- src/components/header/GoBackHeaderStyles.ts
- src/components/navbar/BottomBar.tsx
- src/components/navbar/NavTab.tsx
- src/components/navbar/TopBar.styles.ts
- src/components/navbar/TopBar.tsx
- src/pages/alarm/index.tsx
- src/pages/contest/index.tsx
- src/pages/index.tsx
- src/pages/mypage/index.tsx
- src/pages/mypage/setting/index.tsx
- src/styles/contest/index.styles.ts
- src/styles/index.styles.ts
- 메인 페이지 CSS 수정
- Navbar CSS 및 기능 수정
- 미구현 기능 및 에러 처리
<br/>
- 신규 기능 추가
- 버그 수정
- 리펙토링
<br/>
- 없습니다.
<br/><br/>
> [fix&design] 전체 페이지 및 컴포넌트 CSS 수정 / 에러 처리

- src/api/account/accountApi.ts
- src/atoms/roleAtom.ts
- src/components/area/areaComponent.ts
- src/interfaces/accountInterface.ts
- src/pages/_app.tsx
- src/pages/auth/findId.tsx
- src/pages/auth/findPw.tsx
- src/pages/auth/findinfo.tsx
- src/pages/auth/login.tsx
- src/pages/auth/signup.tsx
- src/pages/contest/index.tsx
- src/pages/index.tsx
- src/pages/mypage/setting/index.tsx
- src/pages/participate/check-weight-sector.tsx
- src/styles/auth/find-info.styles.ts
- 각종 버그픽스
- 아이디찾기 및 비밀번호찾기 페이지 매핑
- JWT 토큰 Local storage 저장 및 유지 (로그인 유지)
- 정보 없을 시, 로그인페이지로 리다이렉션 유도
<br/>
- 신규 기능 추가
- 리펙토링
<br/>
- 아이디/비밀번호찾기 페이지 구현 必
<br/><br/>
> [feat] Maintain Login with Local Storage

- src/pages/_app.tsx
- src/pages/auth/findId.tsx
- src/pages/auth/findPw.tsx
- src/pages/index.tsx
- src/styles/auth/find-info.styles.ts
- src/styles/auth/role-select.styles.ts
- 아이디 찾기
- 비밀번호 찾기
- jwt 로컬 스토리지 정보 버그수정
<br/>
- 신규 기능 추가
- 디자인 수정
- 리펙토링
<br/>
- 없음
<br/><br/>
> [Fead] Find ID & Password & Bug fix about jwt LocalStorage

- src/atoms/contestAtom.ts
- src/atoms/roleAtom.ts
- src/interfaces/contestInterface.ts
- src/interfaces/roleInterface.ts
- src/pages/auth/login.tsx
- src/pages/contest/[id].tsx
- src/pages/contest/player-search/[id].tsx
- src/pages/contest/result-input/[id].tsx
- src/pages/contest/result/[id].tsx
- src/pages/participate/check-weight-sector.tsx
- src/pages/participate/choice-role.tsx
- src/pages/participate/payment.tsx
- src/pages/participate/terms.tsx
- src/styles/contest/result-input.styles.ts
- src/styles/participate/check-weight-sector.styles.ts
- src/styles/participate/choice-roles.styles.ts
- 참가 역할(선수/관람객) 선택 구현
- 대회 참가 및 결제 서버연동
- 대회 결과 및 대회 결과 입력 페이지 구현
- 대회 결과 입력 서버연동
<br/>
- 신규 기능 추가
<br/>
- 없습니다.
<br/><br/>
> [feat] 대회 참가 / 대회 결과 입력 페이지 서버 연동 완료

- src/atoms/contestAtom.ts
- src/pages/participate/apply-success.tsx
- src/pages/participate/payment.tsx
- src/pages/participate/terms.tsx
- 대회 참가 로직 마무리
- 결제기능 서버연동 완료
<br/>
- 신규 기능 추가
- 버그 수정
<br/>
- 없습니다.
<br/><br/>
> [fix] 대회 참가 로직 최종 마무리

- src/pages/mypage/contest/index.tsx
- src/pages/participate/apply-success.tsx
- src/pages/participate/payment.tsx
- src/pages/participate/terms.tsx
- 모바일 결제 기능 추가
<br/>
- 신규 기능 추가
- 버그 수정
<br/>
- 없습니다.
<br/><br/>
> [feat] 모바일 결제 기능 추가

- src/pages/participate/apply-success.tsx
- 모바일 결제 기능 구현
<br/>
- 신규 기능 추가
<br/>
- 없습니다.
<br/><br/>
> [feat] 모바일 결제 기능 구현 2

- src/pages/contest/[id].tsx
- src/pages/participate/apply-success.tsx
- src/pages/participate/choice-role.tsx
- src/pages/participate/payment.tsx
- 모바일 결제 버그 수정
<br/>
- 버그 수정
<br/>
- 없습니다.
<br/><br/>
> [fix] 모바일 결제 버그 수정

- src/pages/contest/[id].tsx
- src/pages/participate/apply-success.tsx
- 모바일 결제 오류 수정
<br/>
- 버그 수정
<br/>
- 없습니다.
<br/><br/>
> [fix] Bugfix mobile payment 2

- src/pages/participate/apply-success.tsx
- 모바일 결제 최종 오류 수정
<br/>
- 버그 수정
<br/>
- 없습니다.
<br/><br/>
> [fix] 모바일 결제 최종 오류 수정

- src/pages/contest/index.tsx
- src/pages/participate/apply-success.tsx
- 모바일 결제 최종 수정
<br/>
- 버그 수정
<br/>
- 없습니다.
<br/><br/>
> [fix] 모바일 결제 최종 수정

- package-lock.json
- package.json
- src/atoms/contestAtom.ts
- src/atoms/modalAtom.ts
- src/components/area/areaComponent.ts
- src/components/button/buttonComponent.ts
- src/components/card/SurveyCard.styles.ts
- src/components/card/SurveyCard.tsx
- src/components/card/SurveyEndCard.tsx
- src/components/web/checkbox/NumCheckBox.tsx
- src/components/web/cropper/ImageCropper.tsx
- src/components/web/modal/CropModal.tsx
- src/components/web/modal/RuleTermModal.tsx
- src/components/web/modal/SectorWeightModal.tsx
- src/components/web/modal/SurveyModal.tsx
- src/interfaces/contestInterface.ts
- src/pages/register/contest-detail.tsx
- src/pages/register/contest-info.tsx
- src/pages/register/rules-and-terms.tsx
- src/pages/register/sector-and-weight.tsx
- src/pages/register/survey.tsx
- src/styles/index.styles.ts
- src/styles/register/contest-detail.styles.ts
- src/styles/register/contest-info.styles.ts
- src/styles/register/rules-and-terms.styles.ts
- 대회 포스터 이미지 crop 기능 구현(react-cropper)
- 대회 정보 텍스트 입력 에디터 기능 구현(react-quill)
- 대회 규정 및 약관 페이지 마이그레이션
- 대회 체급 및 부문 페이지 마이그레이션
<br/>
- 코드 리팩토링
- 마이그레이션
<br/>
- 없습니다.
<br/><br/>
> [feat] 대회 생성 프로세스 마이그레이션 완료
